services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry
    container_name: telemetry-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-telemetry
    environment:
      - PORT=${PORT}
    ports:
      - '3001:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: pgadmin-telemetry
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
  
